

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace casestudy
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class newEntities : DbContext
{
    public newEntities()
        : base("name=newEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Filedata> Filedatas { get; set; }

    public virtual DbSet<User> Users { get; set; }

}

}

